// In toàn bộ khoản chi của đơn hàng cho Kế toán.
(function(){
function allowed(){return user().role==='Kế toán'}
function costStatus(x){return x.paymentStatus||'Chờ kế toán xác nhận'}
function printHtml(o){
 var rows=o.costs||[],paid=rows.filter(function(x){return costStatus(x)==='Đã thanh toán'}).reduce(function(s,x){return s+Number(x.amount||0)},0),total=rows.reduce(function(s,x){return s+Number(x.amount||0)},0),logo=new URL('logo-gomita.png',location.href).href;
 var body=rows.map(function(x,i){var classification=[x.expenseKind||'Chi đơn hàng',x.category||x.type||'Chi phí khác'].filter(Boolean).join(' · '),payer=x.payer||'Công ty trả tiền';if(x.creditor)payer+=' · Nợ: '+x.creditor;var recorder=esc(x.by||'');if(x.confirmedBy)recorder+='<br><small>Xác nhận: '+esc(x.confirmedBy)+'</small>';return'<tr><td>'+(i+1)+'</td><td><b>'+esc(x.text||'Khoản chi')+'</b></td><td>'+esc(classification)+'</td><td>'+esc(payer)+'</td><td>'+(x.at?new Date(x.at).toLocaleString('vi-VN'):'—')+'</td><td>'+esc(costStatus(x))+'</td><td>'+recorder+'</td><td>'+esc(x.note||'')+'</td><td class="money">'+money(x.amount).replace('đ','')+'</td></tr>'}).join('');
 if(!body)body='<tr><td colspan="9" class="empty">Đơn hàng chưa có khoản chi.</td></tr>';
 return'<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Bảng khoản chi - '+esc(o.code||'')+'</title><style>@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{font:11px Arial;color:#102a43;margin:0}header{display:grid;grid-template-columns:100px 1fr 200px;align-items:center;border-bottom:3px solid #d89a4a;padding-bottom:9px}header img{width:78px}h1{text-align:center;font-size:20px;margin:0}.company{line-height:1.55}.info{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px 16px;margin:12px 0;padding:10px;border:1px solid #ccd8e4}.info .wide{grid-column:span 2}.section{font-weight:bold;text-transform:uppercase;margin:13px 0 7px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #cbd6e2;padding:6px;vertical-align:top;overflow-wrap:anywhere}th{background:#102a43;color:#fff}th:nth-child(1){width:35px}th:nth-child(2){width:18%}th:nth-child(3){width:12%}th:nth-child(4){width:15%}th:nth-child(5){width:11%}th:nth-child(6){width:11%}th:nth-child(7){width:10%}th:nth-child(8){width:14%}th:nth-child(9){width:10%}td:first-child{text-align:center}.money{text-align:right;font-weight:bold}.empty{text-align:center;padding:20px}.summary{margin-top:10px;margin-left:auto;width:390px;border:1px solid #cbd6e2}.summary div{display:flex;justify-content:space-between;padding:7px 10px;border-bottom:1px solid #e1e7ee}.summary div:last-child{border:0;background:#102a43;color:#fff;font-weight:bold}.footer{margin-top:16px;border-top:2px solid #d89a4a;padding-top:7px;text-align:center;color:#986b35;font-style:italic}</style></head><body><header><img src="'+logo+'"><h1>BẢNG KHOẢN CHI ĐƠN HÀNG</h1><div class="company"><b>CÔNG TY NỘI THẤT GOMITA</b><br>☎ 0837.39.6866<br>🌐 www.gomita.com<br>📍 Hải Phòng</div></header><div class="info"><div><b>Mã đơn:</b> '+esc(o.code||'')+'</div><div><b>Khách hàng:</b> '+esc(o.customer||'')+'</div><div><b>Điện thoại:</b> '+esc(o.phone||'')+'</div><div class="wide"><b>Địa chỉ:</b> '+esc(o.address||'')+'</div><div><b>Ngày in:</b> '+new Date().toLocaleString('vi-VN')+'</div></div><div class="section">Tất cả khoản chi — bao gồm đã và chưa thanh toán</div><table><thead><tr><th>STT</th><th>Nội dung</th><th>Loại / Nhóm</th><th>Người chi / Công nợ</th><th>Ngày ghi nhận</th><th>Trạng thái</th><th>Người lập / xác nhận</th><th>Ghi chú</th><th>Số tiền</th></tr></thead><tbody>'+body+'</tbody></table><div class="summary"><div><span>Đã thanh toán</span><b>'+money(paid)+'</b></div><div><span>Chưa thanh toán</span><b>'+money(total-paid)+'</b></div><div><span>Tổng tất cả khoản chi</span><b>'+money(total)+'</b></div></div><div class="footer">GOMITA — Bảng tổng hợp khoản chi của đơn hàng</div><script>window.onload=function(){setTimeout(function(){window.print()},250)}<\/script></body></html>';
}
function printCosts(o){var w=window.open('','_blank');if(!w)return toast('Trình duyệt đang chặn cửa sổ bản in.');w.document.write(printHtml(o));w.document.close();log(o,'In bảng khoản chi gồm '+(o.costs||[]).length+' khoản');save()}
function bind(o,tab){if(tab!=='costs'||!o||!allowed())return;var head=$('#orderFormBody .formcontent .pagehead');if(!head||head.querySelector('[data-print-costs]'))return;var add=head.querySelector('[data-add="costs"]'),actions=head.querySelector('.actions');if(!actions){actions=document.createElement('div');actions.className='actions';if(add)actions.appendChild(add);head.appendChild(actions)}var button=document.createElement('button');button.type='button';button.dataset.printCosts='1';button.textContent='⎙ In khoản chi';button.onclick=function(){printCosts(o)};actions.insertBefore(button,actions.firstChild)}
var baseOpenOrderCostsPrint=openOrder;openOrder=function(id,tab){baseOpenOrderCostsPrint(id,tab);bind(id?db.orders.find(function(x){return x.id===id}):null,tab||'info')};
})();
