// Tổng hợp khách hàng từ đơn hàng theo số điện thoại.
(function(){'use strict';
var ROLES_OK=['Kế toán','Giám đốc','Phó giám đốc','Admin'],state={q:'',sort:'revenue_desc'};
function canView(r){if(r===undefined){try{r=user().role}catch(e){r=''}}r=String(r||'');return ROLES_OK.includes(r)||r.indexOf('Quản lý')===0}
function phone(v){var x=String(v||'').replace(/\D/g,'');if(x.indexOf('0084')===0)x='0'+x.slice(4);else if(x.indexOf('84')===0)x='0'+x.slice(2);return x}
function orderTime(o){var a=[o.updatedAt,o.createdAt,o.documents&&o.documents.workflowMeta&&o.documents.workflowMeta.stageEnteredAt];for(var i=0;i<a.length;i++){var t=Date.parse(a[i]||'');if(Number.isFinite(t))return t}return 0}
function debtDate(o){var m=o.documents&&o.documents.workflowMeta||{},a=(Array.isArray(m.stageHistory)?m.stageHistory:[]).concat(Array.isArray(o.stageAssignments)?o.stageAssignments:[]),dates=[];a.forEach(function(x){var t;if(x&&x.stage==='Nghiệm thu'&&Number.isFinite(t=Date.parse(x.at||'')))dates.push(t)});return dates.length?Math.min.apply(Math,dates):0}
function build(orders,fn){var map=new Map();fn=fn||calc;(orders||[]).filter(function(o){return o&&!o.deletedAt}).forEach(function(o){var p=phone(o.phone),key=p?'phone:'+p:'order:'+String(o.id||o.code),x=map.get(key);if(!x){x={key:key,code:p?'KH-'+p:'KH-'+String(o.code||o.id||'CHUA-SDT'),phone:p||String(o.phone||''),name:'',address:'',revenue:0,confirmed:0,debt:0,debtDate:0,newest:-1,orders:[]};map.set(key,x)}var c=fn(o)||{},r=Number(c.revenue||0),paid=Number(c.confirmed||0),due=Number(c.debt);if(!Number.isFinite(due))due=r-paid;var dd=debtDate(o),ot=orderTime(o);x.revenue+=r;x.confirmed+=paid;x.debt+=Math.max(0,due);x.orders.push({order:o,revenue:r,confirmed:paid,debt:due,debtDate:due>0?dd:0});if(due>0&&dd&&(!x.debtDate||dd<x.debtDate))x.debtDate=dd;if(ot>=x.newest){x.newest=ot;x.name=String(o.customer||'Chưa có tên');x.address=String(o.address||'');if(!x.phone)x.phone=String(o.phone||'')}});return Array.from(map.values()).map(function(x){x.debt=Math.max(0,x.debt);if(!x.debt)x.debtDate=0;x.orders.sort(function(a,b){return orderTime(b.order)-orderTime(a.order)});return x})}
function moneyV(v){return typeof money==='function'?money(v):Math.round(Number(v||0)).toLocaleString('vi-VN')+'đ'}
function dateV(v){return v?new Date(v).toLocaleDateString('vi-VN'):'—'}
function data(){var a=build(db.orders||[]),q=state.q.trim().toLocaleLowerCase('vi-VN');if(q)a=a.filter(function(x){return[x.code,x.name,x.phone,x.address].join(' ').toLocaleLowerCase('vi-VN').includes(q)});return a.sort(function(a,b){if(state.sort==='revenue_asc')return a.revenue-b.revenue;if(state.sort==='debt_desc')return b.debt-a.debt;if(state.sort==='debt_asc')return a.debt-b.debt;if(state.sort==='name_asc')return a.name.localeCompare(b.name,'vi');return b.revenue-a.revenue})}
function renderCustomers(){var view=document.getElementById('customersView');if(!view||!canView())return;var rows=data(),all=build(db.orders||[]),rev=all.reduce(function(s,x){return s+x.revenue},0),debt=all.reduce(function(s,x){return s+x.debt},0);document.getElementById('customerMetrics').innerHTML=[['Tổng khách hàng',all.length],['Tổng doanh thu',moneyV(rev)],['Tổng công nợ',moneyV(debt)],['Khách còn nợ',all.filter(function(x){return x.debt>0}).length]].map(function(x){return'<div class="customer-metric"><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>'}).join('');var box=document.getElementById('customersContent');if(!rows.length){box.innerHTML='<div class="empty-state"><div class="empty-icon">♙</div><h3>Không tìm thấy khách hàng</h3><p>Hãy thử từ khóa khác hoặc kiểm tra dữ liệu đơn hàng.</p></div>';return}box.innerHTML='<div class="customer-table-wrap"><table class="data customer-table"><thead><tr><th>Mã khách hàng</th><th>Khách hàng</th><th>Số điện thoại</th><th>Địa chỉ</th><th>Số đơn</th><th>Doanh thu</th><th>Công nợ</th><th>Ngày công nợ</th><th></th></tr></thead><tbody>'+rows.map(function(x){return'<tr data-customer="'+esc(x.key)+'"><td><b>'+esc(x.code)+'</b></td><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.phone||'—')+'</td><td>'+esc(x.address||'—')+'</td><td>'+x.orders.length+'</td><td><b>'+moneyV(x.revenue)+'</b></td><td class="'+(x.debt>0?'danger':'')+'"><b>'+moneyV(x.debt)+'</b></td><td>'+dateV(x.debtDate)+'</td><td><button type="button">Xem đơn</button></td></tr>'}).join('')+'</tbody></table></div>';box.querySelectorAll('[data-customer]').forEach(function(r){r.onclick=function(){openCustomer(r.dataset.customer)}})}
function openCustomer(key){var x=build(db.orders||[]).find(function(v){return v.key===key});if(!x)return;var dialog=document.getElementById('quickDialog');document.getElementById('quickTitle').textContent=x.name+' · '+x.code;document.getElementById('quickBody').innerHTML='<div class="formcontent"><div class="customer-detail-head"><div><small>Số điện thoại</small><b>'+esc(x.phone||'—')+'</b></div><div><small>Địa chỉ mới nhất</small><b>'+esc(x.address||'—')+'</b></div><div><small>Tổng doanh thu</small><b>'+moneyV(x.revenue)+'</b></div><div><small>Còn nợ</small><b class="'+(x.debt>0?'danger':'')+'">'+moneyV(x.debt)+'</b></div></div><div class="customer-table-wrap"><table class="data"><thead><tr><th>Mã đơn</th><th>Tên trên đơn</th><th>Trạng thái</th><th>Doanh thu</th><th>Đã thu</th><th>Còn nợ</th><th>Ngày công nợ</th><th></th></tr></thead><tbody>'+x.orders.map(function(r){var o=r.order;return'<tr><td><b>'+esc(o.code||'—')+'</b></td><td>'+esc(o.customer||'—')+'</td><td>'+esc(o.stage||'—')+'</td><td>'+moneyV(r.revenue)+'</td><td>'+moneyV(r.confirmed)+'</td><td class="'+(r.debt>0?'danger':'')+'">'+moneyV(Math.max(0,r.debt))+'</td><td>'+dateV(r.debtDate)+'</td><td><button type="button" data-order="'+esc(o.id)+'">Mở đơn</button></td></tr>'}).join('')+'</tbody></table></div></div><div class="modalactions"><button value="cancel">Đóng</button></div>';dialog.showModal();document.querySelectorAll('[data-order]').forEach(function(b){b.onclick=function(){dialog.close();openOrder(b.dataset.order)}})}
function access(){var b=document.querySelector('.nav[data-view="customers"]'),ok=canView();if(b)b.style.display=ok?'':'none';var v=document.getElementById('customersView');if(!ok&&v&&v.classList.contains('active')){document.querySelectorAll('.nav,.view').forEach(function(x){x.classList.remove('active')});document.querySelector('.nav[data-view="kanban"]').classList.add('active');document.getElementById('kanbanView').classList.add('active')}}
var css=document.createElement('style');css.textContent='.customer-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:14px}.customer-metric{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px 16px}.customer-metric small,.customer-detail-head small{display:block;color:var(--muted);margin-bottom:5px}.customer-metric strong{font-size:20px}.customer-table-wrap{overflow:auto}.customer-table{min-width:1050px}.customer-table tbody tr{cursor:pointer}.customer-detail-head{display:grid;grid-template-columns:1fr 2fr 1fr 1fr;gap:10px;margin-bottom:15px}.customer-detail-head>div{border:1px solid var(--line);border-radius:10px;padding:11px;background:#fbfcfe}@media(max-width:800px){.customer-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.customer-detail-head{grid-template-columns:1fr}.customers-pagehead{align-items:stretch}.customers-pagehead .toolbar{width:100%}}';document.head.appendChild(css);
var nav=document.querySelector('.nav[data-view="customers"]');nav.addEventListener('click',function(){if(!canView())return;document.querySelectorAll('.nav,.view').forEach(function(x){x.classList.remove('active')});nav.classList.add('active');document.getElementById('customersView').classList.add('active');renderCustomers()});document.getElementById('customerSearch').oninput=function(e){state.q=e.target.value;renderCustomers()};document.getElementById('customerSort').onchange=function(e){state.sort=e.target.value;renderCustomers()};var base=render;render=function(){var r=base();access();if(document.getElementById('customersView').classList.contains('active'))renderCustomers();return r};access();window.GOMITA_CUSTOMERS={normalizePhone:phone,canViewCustomers:canView,acceptanceAt:debtDate,buildCustomers:build,renderCustomers:renderCustomers};
})();
