-- Gomita Flow - PostgreSQL / Supabase schema (MVP production-ready foundation)
create extension if not exists pgcrypto;
create type app_role as enum ('order_manager','production_manager','accountant','director','deput_director','admin');
create type order_stage as enum ('intake','design','quotation','file','production','installation','acceptance','completed');
create table profiles(id uuid primary key references auth.users(id), full_name text not null, role app_role not null, can_edit_all boolean default false, active boolean default true);
create table orders(id uuid primary key default gen_random_uuid(), code text unique not null, customer_name text not null, address text not null, phone text not null, content text, stage order_stage not null default 'intake', owner_id uuid references profiles(id), priority text check(priority in ('urgent','normal','not_urgent')), due_date date, next_action text, note text, zalo_note text, estimated_price numeric(15,2) default 0, quoted_price numeric(15,2) default 0, locked boolean default false, created_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table order_extras(id uuid primary key default gen_random_uuid(), order_id uuid references orders on delete cascade, description text not null, amount numeric(15,2) not null check(amount>=0), kind text check(kind in ('customer_pays','workshop_pays','internal')), note text, created_by uuid references profiles(id), created_at timestamptz default now());
create table payments(id uuid primary key default gen_random_uuid(), order_id uuid references orders on delete cascade, paid_at date not null, amount numeric(15,2) not null check(amount>0), method text check(method in ('cash','bank_transfer')), status text check(status in ('pending','confirmed')) default 'pending', entered_by uuid references profiles(id), confirmed_by uuid references profiles(id), confirmed_at timestamptz, note text, created_at timestamptz default now());
create table costs(id uuid primary key default gen_random_uuid(), order_id uuid references orders on delete cascade, description text not null, amount numeric(15,2) not null check(amount>=0), kind text check(kind in ('production','accessory','labor','transport','other')), note text, created_by uuid references profiles(id), created_at timestamptz default now());
create table employees(id uuid primary key default gen_random_uuid(), external_code text unique not null, full_name text not null, department text, active boolean default true, base_salary numeric(15,2), allowance numeric(15,2), standard_days numeric(8,2), actual_days numeric(8,2), daily_rate numeric(15,2), sheet_synced_at timestamptz);
create table stage_assignments(id uuid primary key default gen_random_uuid(), order_id uuid references orders on delete cascade, stage order_stage not null, employee_id uuid references employees, work_days numeric(8,2), daily_rate numeric(15,2), status text check(status in ('assigned','finalized')) default 'assigned', note text, entered_by uuid references profiles(id), finalized_at timestamptz, created_at timestamptz default now());
create table activity_logs(id bigserial primary key, order_id uuid references orders on delete cascade, actor_id uuid references profiles(id), action text not null, entity text, old_value jsonb, new_value jsonb, created_at timestamptz default now());
create table settings(key text primary key, value jsonb not null, updated_at timestamptz default now());
create index idx_orders_stage on orders(stage); create index idx_orders_due on orders(due_date); create index idx_orders_customer on orders(customer_name); create index idx_payments_order on payments(order_id); create index idx_costs_order on costs(order_id); create index idx_logs_order on activity_logs(order_id,created_at desc);
create view order_financials as select o.id,o.quoted_price + coalesce((select sum(amount) from order_extras e where e.order_id=o.id and kind='customer_pays'),0) revenue, coalesce((select sum(amount) from payments p where p.order_id=o.id and status='confirmed'),0) collected, coalesce((select sum(amount) from costs c where c.order_id=o.id),0)+coalesce((select sum(amount) from order_extras e where e.order_id=o.id and kind='workshop_pays'),0)+coalesce((select sum(work_days*daily_rate) from stage_assignments a where a.order_id=o.id and status='finalized'),0) total_cost from orders o;
alter table profiles enable row level security; alter table orders enable row level security; alter table payments enable row level security; alter table costs enable row level security; alter table order_extras enable row level security; alter table stage_assignments enable row level security; alter table activity_logs enable row level security;
create policy "authenticated read orders" on orders for select to authenticated using(true);
create policy "authorized update orders" on orders for update to authenticated using(not locked or exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('director','admin')));
create policy "authorized insert orders" on orders for insert to authenticated with check(exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('order_manager','director','admin')));
-- Add equivalent role-scoped policies for child tables before production deployment.
