// Lập dữ liệu nghiệm thu/xuất hóa đơn từ file Dự toán JSON.
(function(){
var ROLES_OK=['Kế toán','Admin'],INTEGER_UNITS=['hệ','cái','bộ'];
function permitted(o){return !!o&&ROLES_OK.includes(user().role)&&calc(o).debt<=0.5&&(o.payments||[]).some(function(p){return p.status==='Đã xác nhận'})}
function payments(o){var cash=0,bank=0;(o.payments||[]).filter(function(p){return p.status==='Đã xác nhận'}).forEach(function(p){if(String(p.method||'').toLowerCase().includes('mặt'))cash+=Number(p.amount||0);else bank+=Number(p.amount||0)});return{cash:cash,bank:bank}}
function unit(v){return String(v||'').trim().toLowerCase().replace(/²/g,'2').replace(/\s+/g,' ')}
function integerUnit(v){return INTEGER_UNITS.includes(unit(v))}
function locks(v){return['m2','md','mét dài','mdai','m dài'].includes(unit(v))?{quantityLocked:false,priceLocked:true}:{quantityLocked:true,priceLocked:false}}
function source(o){return o.documents&&o.documents.estimateFile&&o.documents.estimateFile.estimateSnapshot}
function acceptanceRows(s){var out=[],groups={};(s.rows||[]).forEach(function(x){var g=String(x.groupName||'').trim(),a=Math.round(Number(x.amount!=null?x.amount:Number(x.quantity||0)*Number(x.unitPrice||0)));if(!g){out.push(x);return}var key=unit(g);if(!groups[key]){groups[key]={name:g,unit:'\u0068\u1ec7',quantity:1,unitPrice:0,amount:0,rawAmount:0,groupName:g};out.push(groups[key])}groups[key].rawAmount+=a;groups[key].unitPrice=roundPrice(groups[key].rawAmount);groups[key].amount=groups[key].unitPrice});return out}
function createDraft(o){var s=source(o),p=payments(o);if(!s)return null;return{lockSchemaVersion:3,sourceDocumentVersion:Number(o.documents.estimateFile.version||1),sourceTotal:Number(s.total||0),cashInvoice:p.cash,updatedAt:new Date().toISOString(),updatedBy:user().name,rows:acceptanceRows(s).map(function(x){var k=locks(x.unit),a=Math.round(Number(x.amount!=null?x.amount:Number(x.quantity||0)*Number(x.unitPrice||0))),price=Number(x.unitPrice||0);return{id:uid(),name:x.name,unit:x.unit,quantity:Number(x.quantity),unitPrice:price,amount:a,originalQuantity:Number(x.quantity),originalUnitPrice:price,originalAmount:a,quantityLocked:k.quantityLocked,priceLocked:k.priceLocked,isAdded:false,groupName:x.groupName||''}})}}
function draft(o){o.documents=o.documents||{};if(!o.documents.invoiceDraft){o.documents.invoiceDraft=createDraft(o);if(o.documents.invoiceDraft){var firstBalance=balance(o,o.documents.invoiceDraft);o.documents.invoiceDraft.balanceWarning=firstBalance.ok?'':firstBalance.error}}var d=o.documents.invoiceDraft;if(d&&Number(d.lockSchemaVersion||0)<2){(d.rows||[]).forEach(function(r){if(unit(r.unit)==='md'){r.quantityLocked=false;r.priceLocked=true}});d.lockSchemaVersion=2;save()}return d}
function goal(o,d){var p=payments(o);return p.bank+Math.max(0,Math.min(p.cash,Number(d&&d.cashInvoice||0)))}
function sum(d){return(d.rows||[]).reduce(function(s,r){return s+Math.round(Number(r.amount||0))},0)}
function rate(o,d){return Math.abs(goal(o,d)-Number(d.sourceTotal||0))<300000?.05:.20}
function range(o,d,r){var b=Math.max(0,Number(r.originalAmount||0)),x=rate(o,d);return{min:Math.max(0,Math.floor(b*(1-x))),max:Math.ceil(b*(1+x))}}
function adjustMode(r){if(!r.priceLocked&&Number(r.quantity)>0)return'price';if(!r.quantityLocked&&Number(r.unitPrice)>0)return'quantity';return''}
function roundPrice(v){return Math.max(0,Math.round(Number(v||0)/1000)*1000)}
function setAmount(r,a){a=Math.max(0,Math.round(a));var m=adjustMode(r);if(m==='price'){r.unitPrice=roundPrice(a/Number(r.quantity));r.amount=Math.round(r.quantity*r.unitPrice);return true}if(m==='quantity'){var q=a/Number(r.unitPrice);q=integerUnit(r.unit)?Math.round(q):Math.round(q*10000000)/10000000;r.quantity=q;r.amount=Math.round(r.quantity*r.unitPrice);return q>=0}return false}
function capacity(o,d,r,dir){var b=range(o,d,r),a=Number(r.amount||0);return dir>0?Math.max(0,b.max-a):Math.max(0,a-b.min)}
function money(n){return new Intl.NumberFormat('vi-VN').format(Math.round(Number(n||0)))+'đ'}
function qty(n){return new Intl.NumberFormat('vi-VN',{maximumFractionDigits:7}).format(Number(n||0))}
function checkRow(o,d,r){if(!r.name||!r.unit)return'Thiếu tên hạng mục hoặc ĐVT.';if(r.quantity<=0||r.unitPrice<0)return'Số lượng phải lớn hơn 0 và đơn giá không âm.';if(integerUnit(r.unit)&&!Number.isInteger(Number(r.quantity)))return'ĐVT hệ, cái, bộ bắt buộc có số lượng nguyên.';if(Math.round(Number(r.unitPrice))%1000!==0)return'Đơn giá phải được làm tròn đến hàng nghìn.';var b=range(o,d,r);if(r.amount<b.min-1||r.amount>b.max+1)return'Hạng mục “'+r.name+'” vượt giới hạn '+Math.round(rate(o,d)*100)+'%.';return''}
function gapText(o,d){var x=Math.round(sum(d)-goal(o,d));return x>0?'Đang thừa '+money(x):x<0?'Còn thiếu '+money(-x):''}
function balanceResult(o,d){var x=Math.round(sum(d)-goal(o,d));d.balanceWarning=gapText(o,d);return{ok:x===0,difference:x,error:d.balanceWarning}}
function balance(o,d,exclude){
 var target=goal(o,d),diff=Math.round(target-sum(d));if(diff===0)return balanceResult(o,d);var dir=diff>0?1:-1,rows=d.rows.filter(function(r){return r.id!==exclude&&adjustMode(r)&&capacity(o,d,r,dir)>0});
 if(!rows.length)return balanceResult(o,d);
 for(var pass=0;pass<8&&diff!==0;pass++){dir=diff>0?1:-1;rows=d.rows.filter(function(r){return r.id!==exclude&&adjustMode(r)&&capacity(o,d,r,dir)>0});if(!rows.length)break;var ws=rows.map(function(r){return{r:r,w:Math.max(1,r.amount)*(0.55+Math.random()*.9)}}),tw=ws.reduce(function(s,x){return s+x.w},0),start=diff;ws.forEach(function(x,i){if(diff===0)return;var share=i===ws.length-1?diff:Math.round(start*x.w/tw),take=Math.min(Math.abs(share),capacity(o,d,x.r,dir))*(diff>0?1:-1);setAmount(x.r,x.r.amount+take);diff=Math.round(target-sum(d))})}
 if(diff!==0){var absorb=d.rows.find(function(r){return r.id!==exclude&&!r.quantityLocked&&!integerUnit(r.unit)&&r.unitPrice>0&&capacity(o,d,r,diff>0?1:-1)>=Math.abs(diff)});if(absorb){setAmount(absorb,absorb.amount+diff);diff=Math.round(target-sum(d))}}
 if(diff!==0){var exact=d.rows.find(function(r){return r.id!==exclude&&!r.priceLocked&&r.quantity>0&&capacity(o,d,r,diff>0?1:-1)>=Math.abs(diff)});if(exact){setAmount(exact,exact.amount+diff);diff=Math.round(target-sum(d))}}
 return balanceResult(o,d)
}
function persist(d,msg){d.updatedAt=new Date().toISOString();d.updatedBy=user().name;save();if(msg)toast(msg)}
function view(o){
 var s=source(o);if(!s)return'<div class="empty invoice-empty"><b>Chưa có dữ liệu Dự toán.</b><br>Sale cần tải file JSON Dự toán trong tab Thông tin.</div>';var d=draft(o),p=payments(o),target=goal(o,d),different=d.sourceDocumentVersion!==Number(o.documents.estimateFile.version||1);
 var gap=gapText(o,d),diff=Math.round(sum(d)-target),rows=d.rows.map(function(r,i){return'<tr data-ir="'+r.id+'"><td>'+(i+1)+'</td><td><input data-f="name" value="'+esc(r.name)+'"></td><td><input data-f="unit" value="'+esc(r.unit)+'"></td><td><div class="icell"><input type="number" min="0" step="'+(integerUnit(r.unit)?'1':'.0000001')+'" data-f="quantity" value="'+r.quantity+'" '+(r.quantityLocked?'disabled':'')+'><label><input type="checkbox" data-lock="quantity" '+(r.quantityLocked?'checked':'')+'>Khóa</label></div></td><td><div class="icell"><input type="number" min="0" step="1000" data-f="unitPrice" value="'+r.unitPrice+'" '+(r.priceLocked?'disabled':'')+'><label><input type="checkbox" data-lock="price" '+(r.priceLocked?'checked':'')+'>Khóa</label></div></td><td><input class="iamount" type="number" min="0" step="1" data-f="amount" value="'+Math.round(r.amount)+'" '+(adjustMode(r)?'':'disabled')+'></td><td><button type="button" data-rm="'+r.id+'">×</button></td></tr>'}).join('');
 return (gap?'<div class="alert danger">'+esc(gap)+'</div>':'')+'<div class="itop"><div><small>Chuyển khoản · bắt buộc xuất</small><b>'+money(p.bank)+'</b></div><div><small>Đã thu tiền mặt</small><b>'+money(p.cash)+'</b></div><div><label>Tiền mặt xuất hóa đơn</label><input id="cashInvoice" type="number" min="0" max="'+p.cash+'" value="'+d.cashInvoice+'"></div><div class="itarget"><small>Tổng xuất hóa đơn · gồm VAT</small><b>'+money(target)+'</b></div></div><div class="pagehead ihead"><div><h3>Hạng mục biên bản nghiệm thu</h3><small>Đơn giá làm tròn 1.000đ · Thành tiền = số lượng × đơn giá. <span>Giới hạn '+Math.round(rate(o,d)*100)+'%</span></small></div><div class="actions"><button type="button" id="reloadEstimate" '+(different?'class="danger"':'')+'>Nạp lại dự toán'+(different?' mới':'')+'</button><button type="button" id="redistribute">Phân bố lại</button><button type="button" class="primary" id="addIRow">＋ Thêm hạng mục</button></div></div><div class="itable"><table class="data"><thead><tr><th>STT</th><th>Hạng mục</th><th>ĐVT</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div><div class="isummary"><span>Tổng hạng mục <b class="'+(diff!==0?'danger':'')+'">'+money(sum(d))+'</b></span><span>Số tiền xuất hóa đơn <b>'+money(target)+'</b></span><span>'+(diff>0?'Đang thừa':diff<0?'Còn thiếu':'Đã cân đối')+' <b class="'+(diff!==0?'danger':'')+'">'+money(Math.abs(diff))+'</b></span></div><div class="archive-actions"><button type="button" id="saveIDraft">Lưu phương án</button><button type="button" class="primary" id="printAcceptance" '+(diff!==0?'disabled':'')+'>⎙ In biên bản nghiệm thu</button></div>'
}
function rowOf(d,e){return d.rows.find(function(r){return r.id===e.closest('[data-ir]').dataset.ir})}
function change(o,d,input){
 var r=rowOf(d,input),backup=JSON.parse(JSON.stringify(d.rows)),f=input.dataset.f;if(f==='name'||f==='unit'){r[f]=input.value.trim();if(f==='unit'&&integerUnit(r.unit)&&!Number.isInteger(r.quantity)){d.rows=backup;return toast('ĐVT hệ, cái, bộ không được có số lượng lẻ.')}persist(d);return openOrder(o.id,'invoice')}
 var v=Number(input.value);if(!Number.isFinite(v)||v<0){d.rows=backup;return toast('Giá trị không hợp lệ.')};if(f==='quantity'){if(v<=0||integerUnit(r.unit)&&!Number.isInteger(v)){d.rows=backup;return toast('Số lượng hệ, cái, bộ phải là số nguyên.')}r.quantity=v;r.amount=Math.round(r.quantity*r.unitPrice)}if(f==='unitPrice'){r.unitPrice=roundPrice(v);r.amount=Math.round(r.quantity*r.unitPrice)}if(f==='amount'&&!setAmount(r,v)){d.rows=backup;return toast('Dòng này đã khóa cả số lượng và đơn giá.')};var bad=checkRow(o,d,r);if(bad){d.rows=backup;return toast(bad)}var result=balance(o,d,r.id);if(!result.ok)toast(result.error);persist(d);openOrder(o.id,'invoice')
}
function addRow(o,d){
 $('#quickTitle').textContent='Thêm hạng mục xuất hóa đơn';$('#quickBody').innerHTML='<div class="formcontent"><p class="handoff-note">Nhập ít nhất 2 trong 3 ô. Phần mềm tự tính ô còn lại.</p><div class="grid"><div class="field span2"><label>Hạng mục *</label><input name="iname"></div><div class="field"><label>ĐVT *</label><input name="iunit"></div><div class="field"><label>Số lượng</label><input type="number" min="0" step=".0000001" name="iq"></div><div class="field"><label>Đơn giá (làm tròn 1.000đ)</label><input type="number" min="0" step="1000" name="ip"></div><div class="field"><label>Thành tiền</label><input type="number" min="0" name="ia"></div></div></div><div class="modalactions"><button value="cancel">Hủy</button><button type="button" id="confirmIRow" class="primary">Thêm và cân đối</button></div>';$('#quickDialog').showModal();$('#confirmIRow').onclick=function(){var f=new FormData($('#quickForm')),name=String(f.get('iname')||'').trim(),u=String(f.get('iunit')||'').trim(),raw=[f.get('iq'),f.get('ip'),f.get('ia')],filled=raw.filter(function(v){return String(v).trim()!==''}).length;if(!name||!u||filled<2)return toast('Nhập tên, ĐVT và ít nhất 2 thông số.');var q=Number(raw[0]),p=Number(raw[1]),a=Number(raw[2]),missingQ=String(raw[0]).trim()==='',missingP=String(raw[1]).trim()==='',missingA=String(raw[2]).trim()==='';if(!missingP)p=roundPrice(p);if(missingQ)q=a/p;if(missingP)p=roundPrice(a/q);var calculated=Math.round(q*p);if(missingA||missingP)a=calculated;if(q<=0||p<0||a<0||Math.abs(calculated-Math.round(a))>1)return toast('Số lượng × đơn giá làm tròn 1.000đ chưa khớp thành tiền.');if(integerUnit(u)&&!Number.isInteger(q))return toast('ĐVT hệ, cái, bộ phải có số lượng nguyên.');var k=locks(u),r={id:uid(),name:name,unit:u,quantity:q,unitPrice:p,amount:Math.round(a),originalQuantity:q,originalUnitPrice:p,originalAmount:Math.round(a),quantityLocked:k.quantityLocked,priceLocked:k.priceLocked,isAdded:true},backup=JSON.parse(JSON.stringify(d.rows));d.rows.push(r);var result=balance(o,d,r.id);if(!result.ok)toast(result.error);persist(d,'Đã thêm và cân đối hạng mục');$('#quickDialog').close();openOrder(o.id,'invoice')}}
function removeRow(o,d,id){if(!confirm('Xóa hạng mục và phân bổ lại số tiền?'))return;var backup=JSON.parse(JSON.stringify(d.rows));d.rows=d.rows.filter(function(r){return r.id!==id});var result=balance(o,d);if(!result.ok)toast(result.error);persist(d,'Đã xóa và cân đối lại');openOrder(o.id,'invoice')}
function redistribute(o,d){var backup=JSON.parse(JSON.stringify(d.rows));d.rows.forEach(function(r){if(adjustMode(r)){r.quantity=r.originalQuantity;r.unitPrice=r.originalUnitPrice;r.amount=r.originalAmount}});var result=balance(o,d);if(!result.ok)toast(result.error);persist(d,'Đã tạo phương án phân bố mới');openOrder(o.id,'invoice')}
function printHtml(o,d){var target=goal(o,d),rows=d.rows.map(function(r,i){return'<tr><td>'+(i+1)+'</td><td>'+esc(r.name)+'</td><td>'+esc(r.unit)+'</td><td>'+qty(r.quantity)+'</td><td>'+money(r.unitPrice).replace('đ','')+'</td><td>'+money(r.amount).replace('đ','')+'</td></tr>'}).join(''),logo=new URL('logo-gomita.png',location.href).href;return'<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Biên bản nghiệm thu - '+esc(o.code)+'</title><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font:13px Arial;color:#102a43}header{display:grid;grid-template-columns:110px 1fr 180px;align-items:center;border-bottom:3px solid #d89a4a;padding-bottom:10px}header img{width:88px}h1{text-align:center;font-size:21px}.company{line-height:1.6}.info{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0;padding:12px;border:1px solid #ccd8e4}.section{font-weight:bold;text-transform:uppercase;margin:16px 0 8px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #cbd6e2;padding:7px}th{background:#102a43;color:#fff}td:nth-child(1),td:nth-child(3),td:nth-child(4){text-align:center}td:nth-child(5),td:nth-child(6){text-align:right}.total td{font-weight:bold;background:#edf3f8}.pay{border:1px solid #cbd6e2}.pay div{display:flex;justify-content:space-between;padding:8px 12px;border-bottom:1px solid #e1e7ee}.pay div:last-child{background:#102a43;color:#fff;font-weight:bold}.footer{margin-top:24px;border-top:2px solid #d89a4a;padding:8px;text-align:center;color:#986b35;font-style:italic}</style></head><body><header><img src="'+logo+'"><h1>BIÊN BẢN NGHIỆM THU</h1><div class="company"><b>CÔNG TY NỘI THẤT GOMITA</b><br>☎ 0837.39.6866<br>🌐 www.gomita.com<br>📍 Hải Phòng</div></header><div class="info"><div><b>Khách hàng:</b> '+esc(o.customer)+'</div><div><b>Mã đơn:</b> '+esc(o.code)+'</div><div><b>Địa chỉ:</b> '+esc(o.address)+'</div><div><b>Ngày lập:</b> '+new Date().toLocaleDateString('vi-VN')+'</div></div><div class="section">Danh sách hạng mục nghiệm thu</div><table><thead><tr><th>STT</th><th>Hạng mục</th><th>ĐVT</th><th>SL</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>'+rows+'<tr class="total"><td colspan="5">TỔNG GIÁ TRỊ ĐÃ BAO GỒM VAT</td><td>'+money(target).replace('đ','')+'</td></tr></tbody></table><p>Giá trị trên đã bao gồm VAT.</p><div class="footer">GOMITA — Kiến tạo không gian sống tiện nghi và bền vững</div><script>window.onload=function(){setTimeout(function(){window.print()},250)}<\/script></body></html>'}
function print(o,d){if(sum(d)!==goal(o,d))return toast('Tổng hạng mục chưa khớp số tiền xuất hóa đơn.');var bad=d.rows.map(function(r){return checkRow(o,d,r)}).find(Boolean);if(bad)return toast(bad);var w=window.open('','_blank');if(!w)return toast('Trình duyệt đang chặn cửa sổ bản in.');w.document.write(printHtml(o,d));w.document.close();log(o,'In biên bản nghiệm thu xuất hóa đơn '+money(goal(o,d)));save()}
function bind(o){var d=draft(o);if(!d)return;var cash=$('#cashInvoice');if(cash)cash.onchange=function(){var backup=JSON.parse(JSON.stringify(d.rows)),old=d.cashInvoice,p=payments(o),v=Number(cash.value);if(v<0||v>p.cash){cash.value=old;return toast('Tiền mặt xuất hóa đơn phải từ 0 đến '+money(p.cash)+'.')}d.cashInvoice=v;var result=balance(o,d);if(!result.ok)toast(result.error);persist(d);openOrder(o.id,'invoice')};$$('[data-ir] [data-f]').forEach(function(x){x.onchange=function(){change(o,d,x)}});$$('[data-ir] [data-lock]').forEach(function(x){x.onchange=function(){var r=rowOf(d,x);if(x.dataset.lock==='quantity')r.quantityLocked=x.checked;else r.priceLocked=x.checked;persist(d);openOrder(o.id,'invoice')}});$$('[data-rm]').forEach(function(x){x.onclick=function(){removeRow(o,d,x.dataset.rm)}});$('#addIRow').onclick=function(){addRow(o,d)};$('#redistribute').onclick=function(){redistribute(o,d)};$('#reloadEstimate').onclick=function(){if(!confirm('Nạp lại Dự toán sẽ thay toàn bộ phương án hiện tại?'))return;o.documents.invoiceDraft=createDraft(o);var nd=draft(o),result=balance(o,nd);if(!result.ok)toast(result.error);persist(nd,'Đã nạp lại Dự toán');openOrder(o.id,'invoice')};$('#saveIDraft').onclick=function(){var result=balance(o,d);if(!result.ok)toast(result.error);log(o,'Lưu phương án xuất hóa đơn '+money(goal(o,d)));persist(d,'Đã lưu phương án xuất hóa đơn');openOrder(o.id,'invoice')};$('#printAcceptance').onclick=function(){print(o,d)}}
var css=document.createElement('style');css.textContent='.itop{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:18px}.itop>div{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fbfcfe}.itop small,.itop label{display:block;color:var(--muted);font-size:11px;margin-bottom:6px}.itop b{font-size:17px}.itop input{width:100%}.itarget{background:#102a43!important;color:white}.itarget small{color:#dce9f4!important}.ihead .actions{display:flex;gap:7px;flex-wrap:wrap}.ihead small span{padding:3px 7px;border-radius:9px;background:#fff3d7;color:#8b5a00;font-weight:bold}.itable{overflow:auto}.itable table{min-width:900px}.itable input{width:100%;min-width:90px}.itable td:nth-child(2) input{min-width:180px}.icell label{display:flex;align-items:center;gap:4px;margin-top:5px;font-size:10px;color:var(--muted)}.icell label input{width:auto;min-width:0}.iamount{font-weight:bold}.isummary{display:flex;justify-content:flex-end;gap:22px;padding:14px;margin-top:10px;background:#f1f5f9;border-radius:10px}.invoice-empty{padding:30px}@media(max-width:800px){.itop{grid-template-columns:1fr 1fr}}';document.head.appendChild(css);
var baseOpen=openOrder;openOrder=function(id,tab){var o=id?db.orders.find(function(x){return x.id===id}):null,wants=tab==='invoice';if(wants&&!permitted(o)){toast('Xuất hóa đơn chỉ dành cho Kế toán/Admin khi đơn đã thanh toán đủ.');tab='info'}baseOpen(id,wants?'logs':tab);if(!o||!permitted(o))return;var tabs=$('#orderFormBody .tabs'),logs=tabs&&tabs.querySelector('[data-tab="logs"]');if(tabs&&!tabs.querySelector('[data-tab="invoice"]'))logs.insertAdjacentHTML('afterend','<button type="button" class="tab" data-tab="invoice">Xuất hóa đơn</button>');var b=tabs&&tabs.querySelector('[data-tab="invoice"]');if(b)b.onclick=function(){openOrder(o.id,'invoice')};if(!wants)return;$$('#orderFormBody .tab').forEach(function(x){x.classList.toggle('active',x.dataset.tab==='invoice')});var body=$('#orderFormBody .formcontent');if(body)body.innerHTML=view(o);bind(o)};
})();
