// Khu vực đơn theo dõi và luồng tạm dừng/đưa lại công việc.
(function(){'use strict';
var EARLY=['Tiếp nhận','Thiết kế','Báo giá'],DAY=86400000,MANAGERS=['Quản lý Sale','Quản lý đơn hàng','Quản lý sản xuất','Giám đốc','Phó giám đốc','Admin'],CREATE_ROLES=['Sale','Quản lý Sale','Quản lý đơn hàng','Giám đốc','Admin'],query='';
function current(){try{return user()}catch(e){return{}}}
function canCreateOrder(){return CREATE_ROLES.includes(current().role)}
function applyCreatePermission(){var button=document.getElementById('newOrder');if(button)button.style.display=canCreateOrder()?'':'none'}
function ids(o){var a=Array.isArray(o&&o.saleOwnerIds)?o.saleOwnerIds.filter(Boolean):[];if(o&&o.saleOwnerId&&!a.includes(o.saleOwnerId))a.unshift(o.saleOwnerId);return Array.from(new Set(a))}
function isSale(){return current().role==='Sale'}
function visible(o){return !isSale()||ids(o).includes(current().id)}
function manageable(o){return MANAGERS.includes(current().role)||(isSale()&&ids(o).includes(current().id))}
function meta(o){o.documents=o.documents&&typeof o.documents==='object'?o.documents:{};o.documents.workflowMeta=o.documents.workflowMeta&&typeof o.documents.workflowMeta==='object'?o.documents.workflowMeta:{};var m=o.documents.workflowMeta;m.taskTimeline=Array.isArray(m.taskTimeline)?m.taskTimeline:[];m.watchHistory=Array.isArray(m.watchHistory)?m.watchHistory:[];return m}
function readMeta(o){return o&&o.documents&&o.documents.workflowMeta||{}}
function watch(o){return readMeta(o).watch||{}}
function watched(o){return !!watch(o).active}
function stageAt(o){var m=readMeta(o),n=Date.parse(m.stageEnteredAt||'');if(Number.isFinite(n))return n;var a=Array.isArray(o.stageAssignments)?o.stageAssignments:[];for(var i=a.length-1;i>=0;i--){if(a[i]&&a[i].stage===o.stage){n=Date.parse(a[i].at||'');if(Number.isFinite(n))return n}}n=Date.parse(o.createdAt||'');return Number.isFinite(n)?n:0}
function eligible(o,at){var t=stageAt(o);return !!o&&!o.deletedAt&&!watched(o)&&EARLY.includes(o.stage)&&t>0&&(at||Date.now())-t>=7*DAY}
function saleNames(o){var a=ids(o),names=(db.users||[]).filter(function(u){return a.includes(u.id)}).map(function(u){return u.name});return names.length?names.join(', '):'Chưa giao Sale'}
function stamp(){return new Date().toISOString()}
function event(o,x){var m=meta(o);m.taskTimeline.unshift(Object.assign({id:typeof uid==='function'?uid():Date.now()+'',by:current().name||current().username||'Không rõ',at:stamp()},x))}
function watchedOrders(){var q=query.trim().toLocaleLowerCase('vi-VN');return(db.orders||[]).filter(function(o){return!o.deletedAt&&watched(o)&&visible(o)}).filter(function(o){return!q||[o.code,o.customer,o.phone,o.address,saleNames(o)].join(' ').toLocaleLowerCase('vi-VN').includes(q)}).sort(function(a,b){return Date.parse(watch(b).at||'')-Date.parse(watch(a).at||'')})}
function renderWatch(){var box=document.getElementById('watchContent');if(!box)return;var rows=watchedOrders(),badge=document.getElementById('watchCount');if(badge)badge.textContent=rows.length;box.innerHTML=rows.length?'<div class="watch-table-wrap"><table class="data watch-table"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Bước tạm dừng</th><th>Sale phụ trách</th><th>Việc đang dở</th><th>Chuyển theo dõi</th><th>Lý do</th><th></th></tr></thead><tbody>'+rows.map(function(o){var w=watch(o),m=readMeta(o);return'<tr><td><b>'+esc(o.code||'—')+'</b></td><td><b>'+esc(o.customer||'—')+'</b><br><small>'+esc(o.phone||'')+' · '+esc(o.address||'')+'</small></td><td>'+esc(w.previousStage||o.stage)+'</td><td>'+esc(saleNames(o))+'</td><td>'+esc(o.next||'Chưa có việc tiếp theo')+(m.nextDeadline?'<br><small>Hạn '+new Date(m.nextDeadline+'T00:00:00').toLocaleDateString('vi-VN')+'</small>':'')+'</td><td>'+new Date(w.at).toLocaleString('vi-VN')+'<br><small>'+esc(w.by||'')+'</small></td><td>'+esc(w.reason||'—')+'</td><td><div class="row-actions"><button type="button" data-watch-open="'+esc(o.id)+'">Mở đơn</button>'+(manageable(o)?'<button type="button" class="primary" data-watch-return="'+esc(o.id)+'">Đưa lại công việc</button>':'')+'</div></td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty-state"><div class="empty-icon">◉</div><h3>Chưa có đơn theo dõi</h3><p>Đơn ở Tiếp nhận, Thiết kế hoặc Báo giá quá 7 ngày có thể chuyển vào đây.</p></div>';box.querySelectorAll('[data-watch-open]').forEach(function(b){b.onclick=function(){openOrder(b.dataset.watchOpen)}});box.querySelectorAll('[data-watch-return]').forEach(function(b){b.onclick=function(){returnDialog(db.orders.find(function(o){return o.id===b.dataset.watchReturn}))}})}
function startDialog(o){if(!eligible(o))return toast('Đơn chỉ được chuyển sang Theo dõi khi nằm ở Tiếp nhận, Thiết kế hoặc Báo giá đủ 7 ngày.');if(!manageable(o))return toast('Bạn không có quyền chuyển đơn này sang Theo dõi.');$('#quickTitle').textContent='Chuyển đơn sang Theo dõi';$('#quickBody').innerHTML='<div class="formcontent"><div class="completed-task"><small>Đơn hàng</small><b>'+esc(o.code)+' · '+esc(o.customer)+'</b><span>Đang ở bước '+esc(o.stage)+'</span></div><div class="field"><label>Lý do chuyển theo dõi *</label><textarea name="watchReason" rows="3" placeholder="Ví dụ: Khách chưa chốt thời gian triển khai"></textarea></div></div><div class="modalactions"><button value="cancel">Hủy</button><button type="button" id="confirmWatch" class="primary">Chuyển sang Theo dõi</button></div>';$('#quickDialog').showModal();$('#confirmWatch').onclick=function(){var reason=String($('#quickForm [name="watchReason"]').value||'').trim();if(!reason)return toast('Bắt buộc nhập lý do chuyển theo dõi.');var m=meta(o),at=stamp();m.watch={active:true,previousStage:o.stage,at:at,by:current().name||current().username||'',reason:reason,wasLocked:!!o.locked};m.watchHistory.push({action:'start',stage:o.stage,at:at,by:m.watch.by,reason:reason});event(o,{type:'watch-started',title:'Chuyển sang Theo dõi',task:o.next,deadline:m.nextDeadline,reason:reason});o.locked=true;log(o,'Chuyển đơn sang Theo dõi · '+reason);$('#quickDialog').close();$('#orderDialog')?.close();render();toast('Đã chuyển đơn sang Theo dõi.')}}
function returnDialog(o){if(!o||!watched(o))return;if(!manageable(o))return toast('Bạn không có quyền đưa đơn này lại công việc.');var m=meta(o),w=watch(o);$('#quickTitle').textContent='Đưa đơn lại công việc';$('#quickBody').innerHTML='<div class="formcontent"><div class="completed-task"><small>Trở lại bước</small><b>'+esc(w.previousStage||o.stage)+'</b><span>'+esc(o.code)+' · '+esc(o.customer)+'</span></div><div class="grid"><div class="field span2"><label>Việc tiếp theo *</label><input name="watchNext" value="'+esc(o.next||'')+'"></div><div class="field"><label>Deadline mới *</label><input type="date" name="watchDeadline" min="'+today()+'"></div><div class="field span3"><label>Ghi chú đưa lại công việc</label><textarea name="watchReturnNote" rows="2"></textarea></div></div></div><div class="modalactions"><button value="cancel">Hủy</button><button type="button" id="confirmWatchReturn" class="primary">Đưa lại Kanban</button></div>';$('#quickDialog').showModal();$('#confirmWatchReturn').onclick=function(){var n=String($('#quickForm [name="watchNext"]').value||'').trim(),d=String($('#quickForm [name="watchDeadline"]').value||'').trim(),note=String($('#quickForm [name="watchReturnNote"]').value||'').trim();if(!n||!d)return toast('Bắt buộc nhập việc tiếp theo và deadline mới.');var old=o.next||'',od=m.nextDeadline||'',at=stamp();w.active=false;w.returnedAt=at;w.returnedBy=current().name||current().username||'';w.returnNote=note;m.watchHistory.push({action:'return',stage:w.previousStage||o.stage,at:at,by:w.returnedBy,note:note});o.locked=!!w.wasLocked;o.next=n;m.nextDeadline=d;m.stageEnteredAt=at;m.stageOrderKey=Date.parse(at);event(o,{type:old?'task-edited':'task-created',title:'Đưa lại vào công việc',task:n,deadline:d,oldTask:old,oldDeadline:od,reason:note});log(o,'Đưa đơn từ Theo dõi trở lại '+o.stage+' · Việc tiếp theo: '+n);$('#quickDialog').close();render();toast('Đã đưa đơn trở lại Kanban.')}}
function filterOrders(fn){var all=db.orders;db.orders=all.filter(function(o){return!watched(o)});try{return fn()}finally{db.orders=all}}
var baseBoard=renderBoard;renderBoard=function(){return filterOrders(function(){return baseBoard()})};var baseReports=renderReports;renderReports=function(){return filterOrders(function(){return baseReports()})};var baseReport=renderReport;renderReport=function(type){return filterOrders(function(){return baseReport(type)})};
var baseOpen=openOrder;openOrder=function(id,tab){if(!id&&!canCreateOrder()){toast('Bạn không có quyền tạo đơn mới.');return}var result=baseOpen(id,tab),o=id?db.orders.find(function(x){return x.id===id}):null;if(!o||tab&&tab!=='info')return result;var content=$('#orderFormBody .formcontent'),actions=$('#orderFormBody .modalactions');if(watched(o)&&content&&!content.querySelector('.watch-banner'))content.insertAdjacentHTML('afterbegin','<div class="locked watch-banner">◉ Đơn đang ở khu vực Theo dõi · tạm dừng tại '+esc(watch(o).previousStage||o.stage)+'</div>');if(actions&&manageable(o)){if(watched(o)&&!actions.querySelector('#returnWatchOrder')){actions.insertAdjacentHTML('afterbegin','<button type="button" id="returnWatchOrder" class="primary">Đưa lại công việc</button>');$('#returnWatchOrder').onclick=function(){returnDialog(o)}}else if(eligible(o)&&!actions.querySelector('#moveToWatch')){actions.insertAdjacentHTML('afterbegin','<button type="button" id="moveToWatch">Chuyển sang Theo dõi</button>');$('#moveToWatch').onclick=function(){startDialog(o)}}}return result};
var nav=document.querySelector('.nav[data-view="watch"]');if(nav)nav.addEventListener('click',function(){document.querySelectorAll('.nav,.view').forEach(function(x){x.classList.remove('active')});nav.classList.add('active');document.getElementById('watchView').classList.add('active');renderWatch()});var search=document.getElementById('watchSearch');if(search)search.oninput=function(e){query=e.target.value;renderWatch()};var baseRender=render;render=function(){var r=baseRender();renderWatch();applyCreatePermission();return r};
var style=document.createElement('style');style.textContent='.watch-table-wrap{overflow:auto}.watch-table{min-width:1180px}.watch-table small{color:var(--muted)}.watch-banner{margin-bottom:14px}.nav-count{display:inline-flex;align-items:center;justify-content:center;min-width:18px;height:18px;padding:0 5px;margin-left:3px;border-radius:999px;background:#e7eef8;color:#34557f;font-size:10px}@media(max-width:800px){#watchView .pagehead{align-items:stretch}#watchView .toolbar{width:100%}#watchSearch{width:100%}}';document.head.appendChild(style);renderWatch();applyCreatePermission();window.GOMITA_WATCH={ids:ids,visible:visible,manageable:manageable,watched:watched,eligible:eligible,stageAt:stageAt,canCreateOrder:canCreateOrder};if(db.currentUser&&current().id)render();
})();
